str="RajaRamMohanRoy"
print(str)
print(len(str))
print(str[7])
print(str[2:7])
print(str[2:10:2])
print(str[1:13])
print(str[-2:-8])#no output
print(str[-2:-13:-3])
print(str[2:])
print(str[:8])
print(str[-11:9])
print(str[::])
print(str[::3])
print(str[-2:-5:-1])
print(str[::-1])
print(str[2:10:0])
